### ISSUE TITLE
Peer Review - Repo

### ISSUE THREAD

**Issue by veerleprins** [lisaoude/progressive-web-apps-2021#2]
### Review:
- There is a live demo link at the top right  ✅ 
- The API is described in the README  ✅ ,only you might be able to explain a little more here which endpoints you used or whether this was maybe only 1 or not! 
- Maybe you can also describe something about the packages you downloaded and why this was necessary (I was also advised to do that myself 😄) 
- Perhaps you can tell something about the template engine you use in the top right of your description, etc. 😄 

Good that your commits are now clearer compared to the WAFS course 👍 👍 

### To solve this issue:

- [x] Describe a little more about your API endpoints. 
- [x] Tell us about the packages you use. 
- [x] Optional: Tell something about the template engine at the top right.

**Comment by lisaoude** [comment]
Thanks for the feedback! 😄 
Your feedback was very helpful and has been implemented.
