### ISSUE TITLE
Feedback Lotte 19mrt

### ISSUE THREAD

**Issue by Lottetekulve** [lisaoude/progressive-web-apps-2021#3]
Je code ziet er goed uit. Erg fijn dat je alles hebt opgedeeld in je views en partials. Je doet alles op een logische manier en volgens mij verder geen onnodige dingen gebruikt. Verder lekker up to date met je readme, looks good.

Vraag: 
- Heb jij nu ook al opdracht 1 vraag 2 (tooling) gedaan? 
- Ben je al bezig geweest met opdracht 2?

**Comment by lisaoude** [comment]
Thanks for your feedback! 😄👍
