### ISSUE TITLE
Peer Review - Code

### ISSUE THREAD

**Issue by veerleprins** [lisaoude/progressive-web-apps-2021#4]
### Review:
- Nice that your code now looks structured and that you begin to understand Node.js 👍 🔥 
- You just have commented out quite a bit of code that you don't do anything with / or plan to do something with later. Maybe as a tip you can remove that instead of leaving it in your code itself 😄.
- Maybe you can make your app.js a little more structured! You are now using an arrow function that is immediately opened within your app.use () and that looks a bit waterfall-like. 💧 
- Try to draw 1 line in: promises normal and async await. I see that for example on line 44 of your app.js you use both in the same function. 
- Line 8 in your app.js file says 
```// css file```
But that is not correct. It is not your CSS file that you indicate with it. Maybe you can take a look at what your code does. 😄 

But otherwise it already looks good, keep it up! 👍 

### To Solve this Issue:

- [x] Remove unnecessary code from your comments.
- [x] Try to structure your app.js.
- [x] Choose between normal promises and async await promises.
- [x] Try to understand exactly what your code does.

**Comment by lisaoude** [comment]
Thanks for the feedback! All feedback has been implemented 😄👍
